[package]
name = "adventofcode2021-rs"
version = "0.1.0"
authors = ["Nico Fricke <nico@nifni.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
